In [1]:
import numpy as np

In [2]:
def convolve(x, kernel):
    x_height = x.shape[0]
    x_width = x.shape[1]
    
    kernel_height = kernel.shape[0]
    kernel_width = kernel.shape[1]
    
    H = (kernel_height - 1) // 2
    W = (kernel_width - 1) // 2
    
    out = np.zeros((x_height, x_width))
    # iterate over all the pixel of image X
    for i in np.arange(H, x_height - H):
        for j in np.arange(W, x_width - W):
            sum = 0
            # iterate over the filter
            for k in np.arange(-H, H + 1):
                for l in np.arange(-W, W + 1):
                    # get the corresponding value from image and filter
                    a = x[i + k, j + l]
                    w = kernel[H + k, W + l]
                    sum += (w * a)
            out[i, j] = sum
    return out

In [3]:
x_kernel = np.array([ [-1, 0, 1],
                      [-1, 0, 1],
                      [-1, 0, 1] ])



y_kernel = np.array([ [-1, -1, -1],
                      [0, 0, 0],
                      [1, 1, 1] ])

In [36]:
x = np.random.randint(0, 256, (5, 5), dtype=np.uint8)
print("Input Matrix (5x5):")
print(x)

Input Matrix (5x5):
[[242  31  20 226 243]
 [ 91  36 143  71 152]
 [ 91  66 116 217  80]
 [ 97  78 150  20 225]
 [209 201  41 241  26]]


In [37]:
np.savetxt("Data/test5x5.txt", x, fmt="%d")

In [39]:
x_load = np.loadtxt("Data/test5x5.txt", dtype=np.uint8)

In [42]:
pre_x = convolve(x_load, x_kernel)
print("x_out:\n {}" .format(pre_x))
pre_y = convolve(x_load, y_kernel)
print("\ny_out:\n {}" .format(pre_y))

# calculate the gradient magnitude of vectors
edge_out = np.sqrt(np.power(pre_x, 2) + np.power(pre_y, 2))
edge_out = (edge_out / np.max(edge_out)) * 255
print("\nedge out:\n {}" .format(np.ceil(edge_out)))

x_out:
 [[   0.    0.    0.    0.    0.]
 [   0. -145.  381.  196.    0.]
 [   0.  130.  128.   48.    0.]
 [   0.  -90.  133.   24.    0.]
 [   0.    0.    0.    0.    0.]]

y_out:
 [[   0.    0.    0.    0.    0.]
 [   0.  -20.  122.  -76.    0.]
 [   0.   55.   -2.   29.    0.]
 [   0.  178.   84. -105.    0.]
 [   0.    0.    0.    0.    0.]]

edge out:
 [[  0.   0.   0.   0.   0.]
 [  0.  94. 255. 134.   0.]
 [  0.  90.  82.  36.   0.]
 [  0. 128. 101.  69.   0.]
 [  0.   0.   0.   0.   0.]]


In [35]:
output = convolve(x, x_kernel)
print("\nOutput Matrix after Convolution:")
print(output)


Output Matrix after Convolution:
[[   0.    0.    0.    0.    0.]
 [   0.  107.   88. -169.    0.]
 [   0.  239.  -10.  -34.    0.]
 [   0.   -4.  110.  204.    0.]
 [   0.    0.    0.    0.    0.]]


In [50]:
import numpy as np

# Define the size of the array
ROWS = 128
COLS = 128

# Generate a ROWS x COLS array of random 8-bit integers (0-255)
array = np.random.randint(0, 256, size=(ROWS, COLS))

# Convert the array to C array format
c_array_str = f"int x[ROWS][COLS] = {{\n"
for row in array:
    c_array_str += "    {" + ", ".join(map(str, row)) + "},\n"
c_array_str = c_array_str.rstrip(",\n") + "\n};"

# Save to a text file
with open("c_array.txt", "w") as file:
    file.write(c_array_str)

print("C array saved to c_array_128x128.txt")


C array saved to c_array_128x128.txt
